apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-deployment
  namespace: fd-labs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fd-service-example
    spec:
      containers:
      - name: fd-service-example
        image: fd-dev/fd-service-example
        imagePullPolicy: Never
        ports:
        - containerPort: 39999